### ISSUE TITLE
how combine multiple scale_y_facet layers into one variable?

### ISSUE THREAD

**Issue by junjunlab** [teunbrand/ggh4x#101]
Hi, I have to change the panel y limit ranges for multiple panels, but I found I write a loop for scale_y_facet and save it into variable, then I combine this layer to main plot, but it didn't work. It works only when I add each layer with scale_y_facet to the main plot, here is the exmple code:

**not works:**

```
new_l <- lapply(7:8, function(x){
  scale_y_facet(PANEL == x,limits = c(0,3.5),breaks = NULL)
})

p + new_l
```

**works:**

```
p +
 scale_y_facet(PANEL == 7,limits = c(0,3.5),breaks = NULL) +
 scale_y_facet(PANEL == 8,limits = c(0,3.5),breaks = NULL)
```

Thanks!

**Comment by junjunlab** [comment]
Thanks for your help!
<img src="https://media4.giphy.com/media/dG0HsXfl09q9LTxOy1/giphy.gif"/>

**Comment by teunbrand** [comment]
Should now work in dev version as advertised:

``` r
library(ggh4x)
#> Loading required package: ggplot2

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  facet_grid(drv ~ ., scales = "free_y") +
  lapply(1:3, function(x) {
    scale_y_facet(PANEL == x, limits = c(0, x * 20))
  })
```

![](https://i.imgur.com/RBLVF0S.png)

<sup>Created on 2023-04-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
