### ISSUE TITLE
force_panelsizes: Allow `bigpts` as a valid unit for total_width and total_height

### ISSUE THREAD

**Issue by sergiocorreia** [teunbrand/ggh4x#118]
Currently, `bigpts` is [not allowed](https://github.com/teunbrand/ggh4x/blob/main/R/force_panelsize.R#L68) as a unit for the total_width/height arguments.

However, they do work with the `rows` and `cols` arguments. Would it be possible to allow bigpts?

Thanks!

**Comment by teunbrand** [comment]
Yeah that shouldn't be too difficult to do, I just never saw anyone using bigpts units in the wild so I never bothered to include it.

**Comment by teunbrand** [comment]
This is included in the latest version
