### ISSUE TITLE
Error in legend$train when using "stringlegend"

### ISSUE THREAD

**Issue by heeringa0** [teunbrand/ggh4x#127]
Running:

p <- ggplot(mpg, aes(displ, hwy)) +
geom_point(aes(colour = manufacturer))
p + guides(colour = guide_stringlegend(ncol = 2))
p + scale_colour_viridis_d(guide = "stringlegend")

gives an error:

Warning: Error in legend$train: attempt to apply non-function

**Comment by teunbrand** [comment]
Thanks for the report. Can I inquire which version of ggplot2 and ggh4x you are using?

**Comment by heeringa0** [comment]
Sure.

I reinstalled the two packages, and the problem got solved:

R version 4.3.1
ggplot2 version 3.4.3
ggh4x version 0.2.6

Thanks!


________________________________

**Comment by teunbrand** [comment]
Glad to know that resolved the problem!
