### ISSUE TITLE
Ggplotly will move x-axis back to default position

### ISSUE THREAD

**Issue by meldarionqeusse** [teunbrand/ggh4x#148]
```r
install.packages("ggh4x")
install.packages("plotly")
library(ggh4x)
library(plotly)

df <- data.frame(x = c(0, 1), y=c(-0.2,0.2))

g <- ggplot(df, aes(x, y)) +
  geom_point() +
  theme(axis.line = element_line()) +
  coord_axes_inside(labels_inside = TRUE)
g  #shows xaxis correctly 
ggplotly(g) #displays x axis in default positions
```

## Output of g
![image](https://github.com/teunbrand/ggh4x/assets/21668964/c4b45e3f-9e9f-49d7-a4da-9235a9881fcd)

## Output of ggplotly(g)
![image](https://github.com/teunbrand/ggh4x/assets/21668964/91798c60-4ca6-4e65-b46d-9c0d2dd196d6)

**Comment by teunbrand** [comment]
I empathise with the problem, but there is very little I can do to change this.
For a sizeable part, ggplotly reimplements the build method of ggplots. 
As far as I'm aware, there isn't a way in which extensions can interfere with that custom build method.
So in the current situation, I cannot fix this.
