### ISSUE TITLE
Add compatibility with ggtext::element_markdown()

### ISSUE THREAD

**Issue by NaamanOmar** [teunbrand/ggh4x#156]
element_markdown() is helpful when parsing bold and italics to a ggplot. It is compatible with facet_grid() but not facet_nested(). 

Please consider adding compatibility with ggtext::element_markdown(). Being able to use facet_grid() and italicize my strip labels would be helpful for biologists when the strip is a Genus or species name.

**Comment by teunbrand** [comment]
Hi there, thanks for the report. This has been raised in #153 and #151 as well and is fixed in the github version. Feel free to try it out by using `devtools::install_github("teunbrand/ggh4x")`.
