### ISSUE TITLE
Error in check_object(cols, is_quosures, "a {.fn vars} specification"

### ISSUE THREAD

**Issue by lulu5049** [teunbrand/ggh4x#157]
Thanks for the great package.

I encounter the following problem when I use the facet_grid2 function (using the demo examples ).

```r
> p <- ggplot(mpg, aes(displ, hwy, colour = as.factor(cyl))) + geom_point() +
+     labs(x = "Engine displacement", y = "Highway miles per gallon") +
+     guides(colour = "none")
> p + facet_grid2(vars(year), vars(drv), axes = "all", remove_labels = "y")
Error in check_object(cols, is_quosures, "a {.fn vars} specification",  : 
  could not find function "check_object"
> traceback()
3: .int$grid_as_facets_list(rows, cols)
2: new_grid_facets(rows, cols, scales, space, axes, remove_labels, 
       independent, shrink, labeller, as.table, switch, drop, margins, 
       render_empty, strip, super = FacetGrid2)
1: facet_grid2(vars(year), vars(drv), axes = "all", remove_labels = "y")
```

![image](https://github.com/teunbrand/ggh4x/assets/28507399/35e3f538-bc91-4ce6-95a4-bbca819c5b8f)

Is it a function in other packages?

**Comment by teunbrand** [comment]
The example works fine on my end. What versions of ggh4x and ggplot2 are you using?

**Comment by lulu5049** [comment]
ggplot2: version 3.5.0, ggh4x: version 0.2.8.9000

The code now works in my computer. I cannot reproduce the error. Maybe because I restart my Rstudio.
