### ISSUE TITLE
`guide_stringlegend()` throws `Error in get_layer_key(...) : argument "data" is missing, no default`

### ISSUE THREAD

**Issue by adcascone** [teunbrand/ggh4x#159]
I tried recreating the second set of plots using the code provided in the "String legends" section of the ["Miscellanous" vignette](https://cran.rstudio.com/web/packages/ggh4x/vignettes/Miscellaneous.html), but `guide_stringlegend()` throws the following error: `Error in get_layer_key(...) : argument "data" is missing, no default`

Here is the code I tried:
```
p <- ggplot(mpg, aes(displ, hwy)) + geom_point(aes(colour = class))
p + guides(colour = guide_stringlegend(face = "bold", spacing = 15))
```
![image](https://github.com/teunbrand/ggh4x/assets/70408991/8858c5d7-69dc-4bb9-b980-8862bf7e6b35)

I see that the function's lifecycle is marked as 'questioning' on the function [reference site](https://teunbrand.github.io/ggh4x/reference/guide_stringlegend.html) - are there plans to update this function in future package versions?

Thank you!
Arianna C.

**Comment by teunbrand** [comment]
Hi thanks for inquiring! 

It seems to be working fine on my end, using ggplot2 3.5.1 and ggh4x 0.2.8. 
What version combination of ggplot2 and ggh4x are you using? 

> are there plans to update this function in future package versions?

No I'm in the process of writing a separate package ([gguidance](https://github.com/teunbrand/gguidance)) for guide extensions, where this one will be transferred to.

**Comment by adcascone** [comment]
Thanks for the reply - I'm using ggplot2 3.5.1 and ggh4x 0.2.6

And good to know about transferring this function to the new package - I appreciate the insight!

**Comment by teunbrand** [comment]
I'd recommend updating to 0.2.8, there were some breaking changes in ggplot2 that required some adaptation in ggh4x.

**Comment by teunbrand** [comment]
I'm going to go ahead and assume that updating has fixed the issue. I'll reopen if somebody points out I was mistaken.
