### ISSUE TITLE
S3 guide system deprecated in ggplot2 3.5.0

### ISSUE THREAD

**Issue by jj-9** [teunbrand/ggh4x#160]
Dear Teun van den Brand,

First, thank you for this package which brings a lot of useful features to ggplot2.

The new version of guides in ggplot pops a deprecated advice while using "guide" in scale_x_discrete.

This code of yours is sufficient to get the message :

```
ggplot(mpg, aes(interaction(cyl, class), hwy)) +
  geom_boxplot() +
  scale_x_discrete(guide = "axis_nested")
```

I didn't find a way to workaround this.
Hopefully it will not be a blocking point.

Best regards
JJ

**Comment by teunbrand** [comment]
Hi there,

Thanks for the report! The plan is to eventually move all guides to a separate package, but for now the warning should be harmless.

**Comment by jj-9** [comment]
Dear Teun van den Brand,

thank you very much for your attention.

Regards
JJ

**Comment by teunbrand** [comment]
Closing this in favour of #174.
