### ISSUE TITLE
Self-plagiarise `at_panel()` function

### ISSUE THREAD

**Issue by teunbrand** [teunbrand/ggh4x#162]
I had a good brainfart last week that I wish to immortalise as a function.
Code in https://github.com/teunbrand/ggplot-extension-club/discussions/16#discussioncomment-9843972 for context.

**Comment by EvaMaeRey** [comment]
Why not use x = I(.1), y = (.1)  in the examples?  And maybe throw some justification in there?

**Comment by teunbrand** [comment]
I would like that better too, but because that is a 3.5.0 feature and I depend on 3.4.2 I cannot.
I'm not throwing the justification in there as it distracts from the thing that I want to use the examples for, which is to showcase how to use the `expr` argument.

**Comment by EvaMaeRey** [comment]
Ah, right, 3.5.0.  And makes sense not to stay focused in the example!

**Comment by teunbrand** [comment]
Fixed by 8223cec
