### ISSUE TITLE
Let `labels_inside` argument of `coord_axes_inside()` support `"x"`, `"y"` independently?

### ISSUE THREAD

**Issue by psychelzh** [teunbrand/ggh4x#167]
For example, in such circumstances, we could only let X axis labels be inside and let Y axis labels be outside:

``` r
library(ggplot2)
dat <- expand.grid(
  id = letters[1:3],
  time = 1:100
) |> 
  dplyr::mutate(y = rnorm(dplyr::n()) * 1000)
ggplot(dat, aes(x = time, y = y)) +
  geom_line() +
  facet_grid(cols = vars(id)) +
  ggh4x::coord_axes_inside(labels_inside = TRUE) +
  theme_classic()
```

![](https://i.imgur.com/q4fl2gz.png)

<sup>Created on 2024-09-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Thanks I think  this is a good suggestion.
