### ISSUE TITLE
Fill area between two lines with different colors

### ISSUE THREAD

**Issue by Breeze-Hu** [teunbrand/ggh4x#171]
Dear Teun van den Brand,

 ggh4x provides `stat_difference` as a nice implementation of area fill color change (y1>y2 or y1<y2). Recently, I've come across some needs to implement more complex scenarios for changing the fill color between folds, as mentioned in the link below:
https://stackoverflow.com/questions/77430957/fill-area-between-two-lines-with-different-colors-based-on-condition-in-ggplot2

I would like to know if you would like to further improve `stat_difference` or create a new function?

Best regards
Hu

**Comment by teunbrand** [comment]
Hello Hu,

I'm not sure what exactly you mean with 'more complex scenarios'.
The SO question you link to has a reasonable answer, so is there something more that you like to do but currently can't?

Best wishes

**Comment by Breeze-Hu** [comment]
Hello ! 
The method in the link does indeed make it possible to realize complex scenarios. The code uses interpolation to make the result (change in fill color) smoother:

```
df2 <- df %>%
  reframe(x = seq(1, 12, length = 500),
          y1 = approx(month, tmean, xout = x)$y,
          y2 = approx(month, tmean_ref, xout = x)$y,
          diff = y1 - y2)
```

What I'm trying to say is could this need be realized using a `stat_difference like function` combined with `fill=y1-y2`? Rather than having to use interpolation outside of plotting to **create a new dataframe** combined  with `geom_segment`.

Best wishes

**Comment by teunbrand** [comment]
Well, `stat_difference()` also uses interpolation, it is just more hidden from users.
The dev version of ggplot2 has the option to use a gradient as the fill for `geom_ribbon()`.
We can use this as follows:

``` r
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.5.1.9000'

df <- data.frame(
  month = c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"),
  tmean = c(20, 22, 20, 28, 30, 32, 34, 33, 30, 27, 24, 18),
  tmean_ref = c(18, 20, 23, 27, 29, 31, 33, 32, 29, 26, 22, 19),
  tano = c(2, 2, -3, 1, 1, 1, 1, 1, 1, 1, 2, -1),
  tano_label = c("+2", "+2", "-3", "+1", "+1", "+1", "+1", "+1", "+1", "+1", "+2", "-1")
)

p <- ggplot(data = df, aes(x = month, group = 1)) +
  geom_line(aes(y = tmean), linewidth = 0.85, lineend = "round", na.rm = TRUE) +
  geom_line(aes(y = tmean_ref, group = 1), linetype = "longdash", na.rm = TRUE) +
  geom_point(aes(y = tmean), na.rm = TRUE) +
  scale_fill_gradient2()

ribbon_aes <- aes(ymin = tmean, ymax = tmean_ref, fill = after_stat(ymin - ymax))

p + geom_ribbon(ribbon_aes)
```

![](https://i.imgur.com/3AUws70.png)

Note however that at the crossover points, the gradient is purple instead of white. You can use `stat_difference()` to fix the colour at these points. It also uses `geom = "ribbon"` and therefore the gradient option is available with the dev version of ggplot2.

``` r
p + ggh4x::stat_difference(ribbon_aes)
```

![](https://i.imgur.com/JFPaDTk.png)

<sup>Created on 2024-10-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

So there isn't really anything I have to in ggh4x do to get the befits of ggplot2's improvements

**Comment by Breeze-Hu** [comment]
Wow, great features! ！
Thank you very much for being the developer of ggplot2 and for providing ggh4x. These features are a great convenience for drawing more complex and intuitive figures.

Really looking forward to the next version of the update coming soon! Hopefully the crossover points issue in the native ggplot will be solved as well, even though ggh4x provides a workaround!

**Comment by teunbrand** [comment]
I'm going to close this issue as it'll take no code changes on ggh4x's behalf for this to become available.
