### ISSUE TITLE
Issue downloading ggh4x package

### ISSUE THREAD

**Issue by cms72** [teunbrand/ggh4x#21]
Hi teunbrand! I can't seem to install the ggh4x package. I get this error everytime ```devtools::install_github("teunbrand/ggh4x")```. I have ggplot2 v3.3.2 installed

```
Downloading GitHub repo teunbrand/ggh4x@HEAD
✓  checking for file ‘/private/var/folders/mz/k82y38y17c12gkyszy_ck9k4lp_bgs/T/RtmpwY7KQW/remotesaee5797902d5/teunbrand-ggh4x-a1fc0b4/DESCRIPTION’ ...
─  preparing ‘ggh4x’: (406ms)
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ggh4x_0.1.0.9000.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/Users/Library/R/3.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘ggh4x’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package ‘ggplot2’ was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package ‘ggh4x’
* removing ‘/Users/Library/R/3.6/library/ggh4x’
Error: Failed to install 'ggh4x' from GitHub:
  (converted from warning) installation of package ‘/var/folders/mz/k82y38y17c12gkyszy_ck9k4lp_bgs/T//RtmpwY7KQW/fileaee577a92c40/ggh4x_0.1.0.9000.tar.gz’ had non-zero exit status
```

**Comment by teunbrand** [comment]
Hello there!

I'm unsure why this happens, it seems silly that it should fail to build when ggplot2 emits a warning message about R versions.
Could you try the code below and let me know if that helps in any way?
It changes a setting for the remotes package that warnings are not considered errors.

```
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
remotes::install_github("teunbrand/ggh4x")
```

Cheers

**Comment by cms72** [comment]
Hi teunbrand! It worked! Thank you 👍

**Comment by KatLeigh11** [comment]
Didn't work for me. Plz help!

> Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
> remotes::install_github("teunbrand/ggh4x")
Downloading GitHub repo teunbrand/ggh4x@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                 
 2: CRAN packages only                  
 3: None                                
 4: withr       (2.1.2 -> 2.3.0 ) [CRAN]
 5: glue        (1.4.1 -> 1.4.2 ) [CRAN]
 6: fansi       (0.4.0 -> 0.4.1 ) [CRAN]
 7: pkgbuild    (1.0.6 -> 1.1.0 ) [CRAN]
 8: callr       (3.4.3 -> 3.4.4 ) [CRAN]
 9: prettyunits (1.0.2 -> 1.1.1 ) [CRAN]
10: backports   (1.1.5 -> 1.1.10) [CRAN]
11: processx    (3.4.1 -> 3.4.4 ) [CRAN]
12: ps          (1.3.0 -> 1.3.4 ) [CRAN]
13: farver      (2.0.1 -> 2.0.3 ) [CRAN]
14: lifecycle   (0.1.0 -> 0.2.0 ) [CRAN]
15: pillar      (1.4.2 -> 1.4.6 ) [CRAN]
16: tibble      (2.1.3 -> 3.0.3 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
rlang       (NA    -> 0.4.7 ) [CRAN]
withr       (2.1.2 -> 2.3.0 ) [CRAN]
glue        (1.4.1 -> 1.4.2 ) [CRAN]
fansi       (0.4.0 -> 0.4.1 ) [CRAN]
pkgbuild    (1.0.6 -> 1.1.0 ) [CRAN]
callr       (3.4.3 -> 3.4.4 ) [CRAN]
prettyunits (1.0.2 -> 1.1.1 ) [CRAN]
backports   (1.1.5 -> 1.1.10) [CRAN]
processx    (3.4.1 -> 3.4.4 ) [CRAN]
ps          (1.3.0 -> 1.3.4 ) [CRAN]
farver      (2.0.1 -> 2.0.3 ) [CRAN]
lifecycle   (0.1.0 -> 0.2.0 ) [CRAN]
pillar      (1.4.2 -> 1.4.6 ) [CRAN]
isoband     (NA    -> 0.2.2 ) [CRAN]
tibble      (2.1.3 -> 3.0.3 ) [CRAN]
Installing 15 packages: rlang, withr, glue, fansi, pkgbuild, callr, prettyunits, backports, processx, ps, farver, lifecycle, pillar, isoband, tibble
Installing packages into ‘C:/Users/kll86/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/rlang_0.4.7.zip'
Content type 'application/zip' length 1146409 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/withr_2.3.0.zip'
Content type 'application/zip' length 209261 bytes (204 KB)
downloaded 204 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/glue_1.4.2.zip'
Content type 'application/zip' length 154743 bytes (151 KB)
downloaded 151 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/fansi_0.4.1.zip'
Content type 'application/zip' length 223761 bytes (218 KB)
downloaded 218 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/pkgbuild_1.1.0.zip'
Content type 'application/zip' length 141134 bytes (137 KB)
downloaded 137 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/callr_3.4.4.zip'
Content type 'application/zip' length 380562 bytes (371 KB)
downloaded 371 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/prettyunits_1.1.1.zip'
Content type 'application/zip' length 37909 bytes (37 KB)
downloaded 37 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/backports_1.1.10.zip'
Content type 'application/zip' length 90873 bytes (88 KB)
downloaded 88 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/processx_3.4.4.zip'
Content type 'application/zip' length 488951 bytes (477 KB)
downloaded 477 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/ps_1.3.4.zip'
Content type 'application/zip' length 333655 bytes (325 KB)
downloaded 325 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/farver_2.0.3.zip'
Content type 'application/zip' length 1912081 bytes (1.8 MB)
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/lifecycle_0.2.0.zip'
Content type 'application/zip' length 101553 bytes (99 KB)
downloaded 99 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/pillar_1.4.6.zip'
Content type 'application/zip' length 182391 bytes (178 KB)
downloaded 178 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/isoband_0.2.2.zip'
Content type 'application/zip' length 3237152 bytes (3.1 MB)
downloaded 3.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/tibble_3.0.3.zip'
Content type 'application/zip' length 415859 bytes (406 KB)
downloaded 406 KB

package ‘rlang’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘rlang’
Warning: restored ‘rlang’
package ‘withr’ successfully unpacked and MD5 sums checked
package ‘glue’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘glue’
Warning: restored ‘glue’
package ‘fansi’ successfully unpacked and MD5 sums checked
package ‘pkgbuild’ successfully unpacked and MD5 sums checked
package ‘callr’ successfully unpacked and MD5 sums checked
package ‘prettyunits’ successfully unpacked and MD5 sums checked
package ‘backports’ successfully unpacked and MD5 sums checked
package ‘processx’ successfully unpacked and MD5 sums checked
package ‘ps’ successfully unpacked and MD5 sums checked
package ‘farver’ successfully unpacked and MD5 sums checked
package ‘lifecycle’ successfully unpacked and MD5 sums checked
package ‘pillar’ successfully unpacked and MD5 sums checked
package ‘isoband’ successfully unpacked and MD5 sums checked
package ‘tibble’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘tibble’
Warning: restored ‘tibble’

The downloaded binary packages are in
	C:\Users\kll86\AppData\Local\Temp\Rtmpcxq0k0\downloaded_packages
√  checking for file 'C:\Users\kll86\AppData\Local\Temp\Rtmpcxq0k0\remotes32d42fb01e2c\teunbrand-ggh4x-73cd31a/DESCRIPTION' (667ms)
-  preparing 'ggh4x': (6.2s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (983ms)
-  checking for empty or unneeded directories
-  building 'ggh4x_0.1.0.9000.tar.gz'
   
Installing package into ‘C:/Users/kll86/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'ggh4x' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for 'ggplot2' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called 'rlang'
Error: package 'ggplot2' could not be loaded
In addition: Warning message:
package 'ggplot2' was built under R version 3.6.3 
Execution halted
ERROR: lazy loading failed for package 'ggh4x'
* removing 'C:/Users/kll86/OneDrive/Documents/R/win-library/3.6/ggh4x'
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\kll86\OneDrive\Documents\R\win-library\3.6\00LOCK\rlang\libs\x64\rlang.dll to C:\Users\kll86\OneDrive\Documents\R\win-library\3.6\rlang\libs\x64\rlang.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\kll86\OneDrive\Documents\R\win-library\3.6\00LOCK\glue\libs\x64\glue.dll to C:\Users\kll86\OneDrive\Documents\R\win-library\3.6\glue\libs\x64\glue.dll: Permission denied
3: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\kll86\OneDrive\Documents\R\win-library\3.6\00LOCK\tibble\libs\x64\tibble.dll to C:\Users\kll86\OneDrive\Documents\R\win-library\3.6\tibble\libs\x64\tibble.dll: Permission denied
4: In i.p(...) :
  installation of package ‘C:/Users/kll86/AppData/Local/Temp/Rtmpcxq0k0/file32d44dbdb8a/ggh4x_0.1.0.9000.tar.gz’ had non-zero exit status
> library(ggh4x)
Error in library(ggh4x) : there is no package called ‘ggh4x’

**Comment by teunbrand** [comment]
Seems like an DLL locking error that is independent from the ggh4x. My best guess is that shutting down all R sessions and then trying again might solve the issue, but other than that I'm not sure what the solution is. Alternatively, you could try installing rlang first and then installing ggh4x.

**Comment by KatLeigh11** [comment]
Thanks for this! I was able to get this to work a couple weeks ago after installing rlang and a few other packages. But now I'm having a new issue. When I try to install ggh4x, I cannot do so. It seems to be catching on ggplot2 and haulting even when I use the force = TRUE option. (I was able to get past the first issue which was Rtools by downloading the older version of Rtools, but ggplot2 is still screwing things up.) Please help!

> remotes::install_github("teunbrand/ggh4x", force = TRUE)
Downloading GitHub repo teunbrand/ggh4x@HEAD
√  checking for file 'C:\Users\kleigh\AppData\Local\Temp\10\Rtmp48MgQn\remotes2ca8147c53b5\teunbrand-ggh4x-0edf548/DESCRIPTION' (601ms)
-  preparing 'ggh4x': (3s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (822ms)
-  checking for empty or unneeded directories
-  building 'ggh4x_0.1.0.9000.tar.gz'
   
Installing package into ‘H:/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'ggh4x' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ggplot2' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'ggh4x'
* removing 'H:/R/win-library/3.6/ggh4x'
Error: Failed to install 'ggh4x' from GitHub:
  (converted from warning) installation of package ‘C:/Users/kleigh/AppData/Local/Temp/10/Rtmp48MgQn/file2ca85ac5735e/ggh4x_0.1.0.9000.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by teunbrand** [comment]
Have you tried the solution posted in the second comment in this thread? Because the error message that you get now, `Error: (converted from warning) package 'ggplot2' was built under R version 3.6.3` seems to be similar to the original issue.

For good measure, I mean this one:

```
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
remotes::install_github("teunbrand/ggh4x")
```

**Comment by KatLeigh11** [comment]
Hi I did and it worked! Thank you
