### ISSUE TITLE
Unable to use facet_nested_wrap

### ISSUE THREAD

**Issue by cms72** [teunbrand/ggh4x#22]
Hi Teunbrand,

I've downloaded the latest package of ggh4x (`remotes::install_github("teunbrand/ggh4x")`)
`library(ggh4x)`

And I'm trying to use facet_nested_wrap, but I keep getting the following error

`Error: 'facet_nested_wrap' is not an exported object from 'namespace:ggh4x'`

**Comment by teunbrand** [comment]
Hello there,

Just as a sanity check, are able to find `facet_wrap2()` in the namespace and are you able to run the following?

```
ggplot(mpg, aes(displ, hwy)) + geom_point()
  + facet_wrap2(vars(class), axes = "full")
```

If this runs without a problem and you're not finding `facet_nested_wrap()`, there might be a bigger problem. However, if this also doesn't run, probably the version you have installed is not the latest, for some reason. (facet_wrap2() and facet_nested_wrap() were added at the same time).

Best,
Teun

**Comment by cms72** [comment]
Hi Teun,

I still get the following problem `Error: 'facet_wrap2' is not an exported object from 'namespace:ggh4x'`, so I guess its the version. I have ggh4x v0.1.0.9 - do I run` remotes::install_github("teunbrand/ggh4x")` again to update this?

**Comment by cms72** [comment]
Hi Teun,

I'm trying to use it for the following question I posted on stackoverflow [https://stackoverflow.com/questions/63434411/how-can-i-combine-multiple-ggplot-graphs-with-different-dataframes-under-the-sam]

**Comment by teunbrand** [comment]
> so I guess its the version

Yes I think it might be the version. 
v0.1.09 is the development version which I update without incrementing the version number. So, when I added facet_nested_wrap I didn't increment the version, so just looking at the version number is slightly misleading in this case.
You could run `remotes::install_github("teunbrand/ggh4x", force = TRUE)` to update to the current version regardless of whether R thinks the version is the same.
Please let me know if that fixes the problem and I'll have a look at the SO question.

Best,
Teun

**Comment by cms72** [comment]
Hi Teun,

Running `remotes::install_github("teunbrand/ggh4x", force = TRUE)` worked. Thanks! And also, thank you for replying to my SO question! Really appreciate it!
