### ISSUE TITLE
Trouble installing package

### ISSUE THREAD

**Issue by KeelinGeorge** [teunbrand/ggh4x#24]
I cant seem to be able to download the package for some reason. I'm not sure how to get past this issue, I have reinstalled backports and I cant find a version 1.1.9

```
 There is a binary version available but the source version is later:
          binary source needs_compilation
backports  1.1.7  1.1.9              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/backports_1.1.7.zip'
Content type 'application/zip' length 81581 bytes (79 KB)
downloaded 79 KB

package ‘backports’ successfully unpacked and MD5 sums checked
Error: Failed to install 'ggh4x' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘backports’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> 
```

**Comment by teunbrand** [comment]
This might be related to #21 though the error is different. The packports package is likely an indirect dependency that I don't really know how to solve, but might be related to what is described [here](https://www.jimhester.com/post/2020-08-20-best-os-for-r/) under 'installation issues'. My best guess is to use the following:

```
remotes::install_github("teunbrand/ggh4x", dependencies = FALSE)
```

Please let me know if that worked out for you.

**Comment by KeelinGeorge** [comment]
Thanks so very much for your quick response, still having issues having tried your solution and the solution in one of the links. Three hours later and I cant seem to solve it!

The package looked like it would solve a big issue for me…..will try again sometime. Just not at all sure why I cannot get it to work.

Thanks again,
Keelin

**Comment by teunbrand** [comment]
Hi there,

At the time of my previous response I also tried to reinstall on windows and I got the same error message as you did. Since then, I think CRAN has uploaded the windows binary for the backports package, so I think you shouldn't get the same error anymore. It occasionally happens that it takes a few days for CRAN to convert source packages to windows binaries, so that windows users don't have to compile these themselves. I'm not guaranteeing it will work now, but it did work on a windows machine for me now.

Best wishes

**Comment by KeelinGeorge** [comment]
Great I will try again this afternoon, fingers crossed! Thanks so very much for your message, its greatly appreciated. And thanks for all the work you put into developing a package like this, its such a useful idea. I have a workaround in place now but it would be great to get this working.

Best wishes
Keelin

**Comment by teunbrand** [comment]
I'm closing this issue for now since this seems to be an issue related to the details of how CRAN operates and it seems unlikely to me that I can do anything from the package's point of view to solve this.
