### ISSUE TITLE
Error in facet_nested(. ~ class + dataset) :    object '.int' not found

### ISSUE THREAD

**Issue by dBenedek** [teunbrand/ggh4x#27]
Hello,

When trying to use `facet_nested`:

```
p <- ggplot(table, aes(fill = difference, x = ind, y = difference)) +
    geom_bar(position="stack", stat="identity", colour="black", width=1) +
    facet_nested(.~class+dataset) + 
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
          legend.position = "bottom", 
          plot.title = element_text(hjust = 0.5)) +
    labs(title=symbol, x ="Sample", y = "Isoform % expression difference") + 
    scale_fill_gradient2(low='darkorange', mid='snow3', high='darkblue', space='Lab')
```
I'm getting this error message: 
`Error in facet_nested(. ~ class + dataset) :    object '.int' not found`

**Comment by teunbrand** [comment]
Hi there,

Have you tried installing the package?
Seems like the error that occured in #8, which seems to surface when the package's namespace is not attached.

Best,

**Comment by dBenedek** [comment]
Yes, however, when I load the package there is a message:
```
The following object is masked _by_ ‘.GlobalEnv’:

    facet_nested
```
I guess this caused the problem.

**Comment by teunbrand** [comment]
That means that you have an object named `facet_nested` in your global environment, so when you use that in you console it will find the one in the global environment first due to the lexical scoping in R. If you use `rm(facet_nested)` and try again afterwards, I suspect it should work.

**Comment by dBenedek** [comment]
OK, thank you!
