### ISSUE TITLE
Error: problem at render time when trying to display 10 or more variables.

### ISSUE THREAD

**Issue by caayala** [teunbrand/ggh4x#5]
Error: a problem at render time when trying to display 10 or more cases.

When I use `facet_nested` with a lot of cases with `geom_col` I get an error. I made an example where I can display correctly 9 cases but it fails with 10. 

``` r
library(tidyverse)
library(ggh4x)

df <- mtcars %>% 
  rownames_to_column('model') %>% 
  mutate(brand = str_extract(model, '(.*?) '),
         brand = coalesce(brand, model))

df %>% 
  slice(1:9) %>% 
  ggplot(aes(x = model, y = mpg)) +
  geom_col() +
  ggh4x::facet_nested(cols = vars(brand, model),
                      scales = 'free_x', space = 'free_x')
```

![](https://i.imgur.com/kNA7MuU.png)

``` r


df %>% 
  slice(1:10) %>% # One aditional case.
  ggplot(aes(x = model, y = mpg)) +
  geom_col() +
  ggh4x::facet_nested(cols = vars(brand, model),
                      scales = 'free_x', space = 'free_x')
#> Error: grobs must either be a single grob or a list of grobs
```

![](https://i.imgur.com/B71tJDw.png)

<sup>Created on 2020-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by teunbrand** [comment]
Hi there,

Thanks for letting me know, I could indeed reproduce this error. I suspect this bug is the result of some recent attempt to fix #4. I'll figure out what might be done to fix this.

Best wishes

**Comment by teunbrand** [comment]
I think this might be fixed now. The following works:

``` r
library(tidyverse)
library(ggh4x)

df <- mtcars %>% 
  rownames_to_column('model') %>% 
  mutate(brand = str_extract(model, '(.*?) '),
         brand = coalesce(brand, model))

df %>% 
  slice(1:10) %>% # One aditional case.
  ggplot(aes(x = model, y = mpg)) +
  geom_col() +
  ggh4x::facet_nested(cols = vars(brand, model),
                      scales = 'free_x', space = 'free_x')
```

![](https://i.imgur.com/vGobhzd.png)

<sup>Created on 2020-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by caayala** [comment]
It works now in my code. Thanks!
