### ISSUE TITLE
ggh4x and rlang 1.0.0

### ISSUE THREAD

**Issue by lionel-** [teunbrand/ggh4x#53]
Hello, I see this problem in revdep checks:

```
  Expected match: "The `nonsense` package is required"
  Actual message: "The package `nonsense` is required for `test`."
```

In general you shouldn’t be testing the contents of error messages that come from another package, since those can change at any point. Can you look into `expect_snapshot()` please? It allows you to monitor changes to messages without causing failures in CRAN checks. See https://testthat.r-lib.org/articles/snapshotting.html

We plan to release rlang 1.0.0 in 2 to 4 weeks.

**Comment by teunbrand** [comment]
Hi Lionel,

Thank you for the heads up, I'll adjust accordingly soon.

Best wishes

**Comment by teunbrand** [comment]
This should be updated on CRAN soon.

**Comment by lionel-** [comment]
Thanks!
