### ISSUE TITLE
 Error unable to collate and parse R files for package 'ggh4x'

### ISSUE THREAD

**Issue by pstils** [teunbrand/ggh4x#66]
Hi, I'm getting the error: 

`ERROR: unable to collate and parse R files for package 'ggh4x'`

When I try to install. Both with devtools and with remotes::install_git

Shoud add: on windows, R version 4.1.2. Though also getting the same problem on linux, fedora, R version 4.1.3

EDIT: works if I install from the commit on the 28th of March: `remotes::install_github("teunbrand/ggh4x/0df72e043c1cc5ade363e077492c18ef10bf12f5")`

**Comment by teunbrand** [comment]
Thanks for letting me know! If you'd want a stable version, you could download the one from CRAN. I'm currently in the process of adding a new feature that might cause some temporary instability. I'll leave this issue open for others to find.

**Comment by pstils** [comment]
ah ok - thanks @teunbrand, I'll do that. Thanks for the package, as well, it's a beaut.

**Comment by teunbrand** [comment]
Alright, I've updated the installation instructions and resolved the installation error if the package is downloaded from GH. I think it'll be fine to close this now.
