### ISSUE TITLE
Custom y axis breaks of facet_wrap2

### ISSUE THREAD

**Issue by showteeth** [teunbrand/ggh4x#71]
Is it possible to custom y axis breaks of **every facet** with `facet_wrap2`?

For example, the follow codes will generate three facets with three different y breaks (`facet 4` with breaks from 1.5 to 3.0, `facet 6` with breaks from 2.75 to 3.5, `facet 8` with breaks from 3.5 to 5.5)
```r
ggplot( mtcars , aes(x=mpg, y=wt, color=as.factor(cyl) )) +
  geom_point(size=3) +
  facet_wrap2(~cyl,scales = "free_y") +
  theme(legend.position="none")
```
![plot](https://i.stack.imgur.com/z6Sp2.png)

And I want to custom y axis breaks of **every facet**, the following is codes to **custom a single one**:
```r
p = ggplot(data=mtcars, aes(x=mpg, y=wt)) +
  geom_point(size=3) +
  theme_classic()
ymax <- ceiling(max(mtcars$wt))
p + scale_y_continuous(breaks = c(0, ymax), expand = c(0, 0)) + expand_limits(y = ymax)
```

![plot2](https://i.stack.imgur.com/IdiFZ.png)

As `Waldi` suggested in [Custom y axis breaks of facet_wrap](https://stackoverflow.com/questions/72962172/custom-y-axis-breaks-of-facet-wrap), this can be solved with [facetscales](https://github.com/zeehio/facetscales), can this be done with `ggh4x`?

**Comment by teunbrand** [comment]
Hi there,

No, `facet_wrap2()` isn't designed for that. However, `facetted_pos_scales()` *is* designed for exactly this, see also [here](https://teunbrand.github.io/ggh4x/articles/Facets.html#position-scales). I've taken the liberty to write an answer to your SO question.

**Comment by showteeth** [comment]
Thanks for your help!
