### ISSUE TITLE
Remove ticks with `facet_wrap2()`

### ISSUE THREAD

**Issue by brunomioto** [teunbrand/ggh4x#77]
My suggestion an argument like `remove_labels = all`, but also with axis ticks.
On my example, I don't thinks it's necessary, but I need them on the 1st column and last row

![image](https://user-images.githubusercontent.com/10459392/187039129-4951ee8e-0577-4391-b9e5-9150311469e7.png)

**Comment by teunbrand** [comment]
Hi there,

I'm sorry I might not understand fully: could you describe it a bit more? So you want to hide all axis labels, except for the eating disorders panel? What exactly should happen to the ticks?

**Comment by brunomioto** [comment]
Oh, sorry for being too simple on my request. 
I just wanted a way to remove the axis ticks, like the option to remove labels that already exists on ggh4x

**Comment by teunbrand** [comment]
Right, got it, thanks! Aren't currently available strategies sufficient for this purpose? You could just add `geom_vline() + geom_hline()` to mimick a tickless axis:

``` r
library(ggplot2)

p <- ggplot(mpg, aes(displ, cty)) +
  geom_point() +
  facet_wrap(~ trans)

p + geom_vline(xintercept = -Inf, size = 1) +
  geom_hline(yintercept = -Inf, size = 1)
```

![](https://i.imgur.com/1lbs9ak.png)

Alternatively:

``` r
p + theme(
    panel.border = ggh4x::element_part_rect(side = "lb", fill = NA, size = 1)
  )
```

![](https://i.imgur.com/OQgvIER.png)

<sup>Created on 2022-08-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by brunomioto** [comment]
Yeah, I think this could work.
Thanks!
