### ISSUE TITLE
Feature request: geom_text labels for unique facets.

### ISSUE THREAD

**Issue by jessexknight** [teunbrand/ggh4x#80]
Similar to [this SE question](https://stackoverflow.com/questions/38414832), I'm trying to add a,b,c,... to a grid of facets so they can be referenced in individually elsewhere. With `scales = 'fixed'`, this is relatively easy, as you can even hardcode the x,y coordinates for a `geom_text` label. However, with `scales = 'free'` (including `facet_grid2` with `independent`), it's a pain to compute all the x,y coordinates for each facet so they labels end up in the same location, visually. This task seems like it could be within the scope of this project, but feel free to ignore... Thanks!

**Comment by teunbrand** [comment]
Could you just use the trick wherein `-Inf` and `Inf` are mapped to the extreme most position?

If you use `geom_label()` and hide the box, you can even (ab)use the padding of the label to get nice paddings to the margin.

I think the idea is pretty nice, but I don't really see how I could improve upon existing ggplot2 solutions except for a simple syntax wrapper.

``` r
library(ggplot2)
x = data.frame(a=c('a','b','a','b'),b=c(1,1,2,2),v=runif(8))
ggplot(x,aes(x=v,y=v)) +
  geom_point() +
  facet_grid('a~b',scales='free') +
  geom_label(
    data = cbind(expand.grid(a = c('a', 'b'), b = c(1, 2)),
                 lab = letters[1:4]),
    aes(x = -Inf, y = Inf, label = lab),
    vjust = 1, hjust = 0, 
    fill = NA, label.size = 0, # Don't show box
    label.padding = unit(5, "mm") # Control margins to panel bounds
  )
```

![](https://i.imgur.com/t846qEt.png)

<sup>Created on 2022-10-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jessexknight** [comment]
Hm, I forgot about that trick. I suppose your solution works too. The exact spacing seems a bit finicky though, especially when printing to different aspect ratios and sizes. With either approach it seems you need to either: a) reconstruct the facet grid data like `expand.grid` or b) use `ggplot_build(g)` after the main plotting calls to collect these things automatically (DRY). Anyways, I understand not supporting but it might help someone if they wander across it here (or [there](https://stackoverflow.com/questions/74113817))

**Comment by teunbrand** [comment]
Those criticisms are fair. The reconstructing the facet structure can be avoided altogether if you use the `after_stat()` function in combination with the `PANEL` internal variable.

``` r
library(ggplot2)

x = data.frame(a=c('a','b','a','b'),b=c(1,1,2,2),v=runif(8))
ggplot(x,aes(x=v,y=v)) +
  geom_point() +
  facet_grid('a~b',scales='free') +
  geom_label(
    aes(x = -Inf, y = Inf, label = after_stat(ifelse(
      duplicated(PANEL), "", letters[as.numeric(PANEL)]
    ))),
    vjust = 1, hjust = 0, 
    fill = NA, label.size = 0, # Don't show box
    label.padding = unit(5, "mm") # Control margins to panel bounds
  )
```

![](https://i.imgur.com/BbJXPyy.png)

If the spacing is too finicky and you purely want relative units for placing your text, the {ggpp} package has just the right function for this.

``` r
x = data.frame(a=c('a','b','a','b'),b=c(1,1,2,2),v=runif(8))
ggplot(x,aes(x=v,y=v)) +
  geom_point() +
  facet_grid('a~b',scales='free') +
  ggpp::geom_text_npc(
    aes(npcx = 0.05, npcy = 0.95,
        label = after_stat(
          ifelse(duplicated(PANEL), "", letters[as.numeric(PANEL)])
        ))
  )
```

![](https://i.imgur.com/MESdpnD.png)

<sup>Created on 2022-10-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I'll cross-post these solutions to SO as well

**Comment by jessexknight** [comment]
Interesting -- thanks for this follow-up (including on SO)!
