### ISSUE TITLE
rbind_dfs() error

### ISSUE THREAD

**Issue by AaronMNew** [teunbrand/ggh4x#81]
Hi, `facet_nested()` has broken for me recently. This is the error I see:

`Error in rbind_dfs(list(x[by], y[by])) : 
  could not find function "rbind_dfs"
> traceback()
13: .int$join_keys(facet_vals, layout, by = vars[vars %in% names(facet_vals)])
12: map_data(...)
11: FUN(X[[i]], ...)
10: lapply(data[-1], self$facet$map_data, layout = self$layout, params = self$facet_params)
9: setup(..., self = self)
8: layout$setup(data, plot$data, plot$plot_env)
7: ggplot_build.ggplot(x)
6: ggplot_build(x)
5: print.ggplot(x)
4: print(x)
3: grid.draw.ggplot(plot)
2: grid.draw(plot)
1: ggsave(figure_path_0, figure.png, 
       width = wi, height = hi)
`

**Comment by teunbrand** [comment]
Hi there,

Could you tell me what version of ggplot2/ggh4x combination this occurs in?
If this is ggplot2 3.6.0 and ggh4x 0.2.2, could I convince you to try the github version?

**Comment by teunbrand** [comment]
Thanks for the confirmation! I guess its time to send the dev version off to CRAN then :)

**Comment by AaronMNew** [comment]
`devtools::install_github("teunbrand/ggh4x")`  Worked for me too, thank you very much (and for facet_nested as well - what an incredible function!)

**Comment by snehanicholson** [comment]
Hi I am having the same issue but installing from github isn't working for me

**Comment by teunbrand** [comment]
@snehanicholson What versions of ggh4x and ggplot2 are you using?

**Comment by kotchaphorn** [comment]
Hi! I am also experiencing the same issue. I have ggplot2 3.4.0 and ggh4x 0.2.3 (reinstalled just now from GitHub as suggested in this thread).

**Comment by teunbrand** [comment]
The recommendation to install from github was from before 0.2.3 was uploaded to CRAN. I'm having trouble getting to trigger the `rbind_dfs()` error from current CRAN ggplot2/ggh4x. Would anybody be able to make a minimal reproducible example for how they've triggered the bug?

This works fine for me (with current CRAN ggplot2/ggh4x):

```r
library(ggh4x)

ggplot(mtcars, aes(mpg, wt)) +
  geom_point() +
  facet_nested(~ vs + cyl)
```

**Comment by kotchaphorn** [comment]
Hi, it works fine for me now. It seems simply reinstalling the package didn't solve the problem. I had to uninstall first, then install fresh from CRAN, both ggplot2 and ggh4x. Not sure what was going on since they were the exact same versions as before. Anyway, thank you for this wonderful package!
