### ISSUE TITLE
Add option to change color of just minor.ticks

### ISSUE THREAD

**Issue by brunomioto** [teunbrand/ggh4x#87]
It's awesome to have `guide = "axis_minor"`!
Can we have a `ggh4x.axis.ticks.color.minor...` or something else?

**Comment by teunbrand** [comment]
Thanks that is a good suggestion! 
However, the ggplot2 guide system is due an overhaul, so I'm not willing to change this now in order for it to fall apart later again.
Probably, after that overhaul, I'll take out all the axis/guide stuff from ggh4x and put it in a different package.

**Comment by teunbrand** [comment]
I'm going to close this issue here as there is a good chance this feature might become part of ggplot2. If not, I'll add it to the new package.
