### ISSUE TITLE
Cannot load package

### ISSUE THREAD

**Issue by angoodkind** [teunbrand/ggh4x#9]
When I try to load the library, I get the error:
```
15:06:58> library(ggh4x)
Error: package or namespace load failed for ‘ggh4x’:
 object 'guide_transform' not found whilst loading namespace 'ggh4x'
```
It seems to be conflicting with the `tidyverse` package. When I restart R, and just load this package, it works.

**Comment by teunbrand** [comment]
Hi, thanks for letting me know.

Is there any chance that the tidyverse package loads ggplot2 v3.2.x instead of v3.3.0?
Some of the functions depend on recent additions of v3.3.0.

Best wishes

**Comment by angoodkind** [comment]
That might be the issue. It seems to be working fine once I updated.
